export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ContentLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
